// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGaTKmSzoZefXqph_FI1fcPq11eFnXqV0',
    appId: '1:549080671954:web:25a5abd5644f765a686f0b',
    messagingSenderId: '549080671954',
    projectId: 'chatapplication-b7358',
    authDomain: 'chatapplication-b7358.firebaseapp.com',
    storageBucket: 'chatapplication-b7358.firebasestorage.app',
    measurementId: 'G-59MPFK0MSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9ZBUwXDda_rnh_1xKwczdMLMkrDw2BKk',
    appId: '1:549080671954:android:40e1bcbcacc1e422686f0b',
    messagingSenderId: '549080671954',
    projectId: 'chatapplication-b7358',
    storageBucket: 'chatapplication-b7358.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjApUrgm-Lp0c8tQD5QQS6lYo1JWXERiI',
    appId: '1:549080671954:ios:2e45002e8dcfea24686f0b',
    messagingSenderId: '549080671954',
    projectId: 'chatapplication-b7358',
    storageBucket: 'chatapplication-b7358.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjApUrgm-Lp0c8tQD5QQS6lYo1JWXERiI',
    appId: '1:549080671954:ios:2e45002e8dcfea24686f0b',
    messagingSenderId: '549080671954',
    projectId: 'chatapplication-b7358',
    storageBucket: 'chatapplication-b7358.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGaTKmSzoZefXqph_FI1fcPq11eFnXqV0',
    appId: '1:549080671954:web:7a6355c59f320e1f686f0b',
    messagingSenderId: '549080671954',
    projectId: 'chatapplication-b7358',
    authDomain: 'chatapplication-b7358.firebaseapp.com',
    storageBucket: 'chatapplication-b7358.firebasestorage.app',
    measurementId: 'G-B2DXZ706YJ',
  );
}
